#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Feb  9 18:11:11 2022

@author: boyd.didsayachai
"""
 
import meteostat  #import weather data
import pandas as pd

from datetime import datetime   
s = datetime(2020,1,1)    #start date
e = datetime(2021,12,31)    #end date
loc = meteostat.Point(42.356683349699290, -71.061666458845140, 75)   #location coordinates
data = meteostat.Daily(loc, s, e) #pull weather data from loc (detroit) between start and end date 
data = data.fetch()  #update the data
measures = ["tsun","snow","prcp","tavg"]  #defining measure variable 
table = data[measures]  #grab min and max temperature from weather api
df = pd.DataFrame(table)
df.to_csv("weatherBostoncommon20-21.csv")
